import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'import',
    'jsdoc',
    'jsx-a11y',
    'promise',
  ],
  categories: {
    correctness: 'off',
    restriction: 'off',
    perf: 'off',
    suspicious: 'off',
    pedantic: 'off',
    style: 'off',
    nursery: 'off',
  },
  options: {
    typeAware: true,
    typeCheck: true,
  },
  jsPlugins: [
    {
      name: 'sonarjs-js',
      specifier: 'eslint-plugin-sonarjs',
    },
  ],
  rules: {
    // eslint – correctness
    'eslint/constructor-super': 'error',
    'eslint/for-direction': 'error',
    'eslint/getter-return': ['error', { allowImplicit: true }],
    'eslint/no-async-promise-executor': 'error',
    'eslint/no-caller': 'error',
    'eslint/no-class-assign': 'error',
    'eslint/no-compare-neg-zero': 'error',
    'eslint/no-cond-assign': 'error',
    'eslint/no-const-assign': 'error',
    'eslint/no-constant-binary-expression': 'error',
    'eslint/no-constant-condition': 'error',
    'eslint/no-control-regex': 'error',
    'eslint/no-debugger': 'error',
    'eslint/no-delete-var': 'error',
    'eslint/no-dupe-class-members': 'error',
    'eslint/no-dupe-else-if': 'error',
    'eslint/no-dupe-keys': 'error',
    'eslint/no-duplicate-case': 'error',
    'eslint/no-empty-character-class': 'error',
    'eslint/no-empty-pattern': 'error',
    'eslint/no-empty-static-block': 'error',
    'eslint/no-eval': 'error',
    'eslint/no-ex-assign': 'error',
    'eslint/no-extra-boolean-cast': 'error',
    'eslint/no-func-assign': 'error',
    'eslint/no-global-assign': 'error',
    'eslint/no-import-assign': 'error',
    'eslint/no-invalid-regexp': 'error',
    'eslint/no-irregular-whitespace': 'error',
    'eslint/no-iterator': 'error',
    'eslint/no-loss-of-precision': 'error',
    'eslint/no-misleading-character-class': 'error',
    'eslint/no-new-native-nonconstructor': 'error',
    'eslint/no-nonoctal-decimal-escape': 'error',
    'eslint/no-obj-calls': 'error',
    'eslint/no-self-assign': 'error',
    'eslint/no-setter-return': 'error',
    'eslint/no-shadow-restricted-names': 'error',
    'eslint/no-sparse-arrays': 'error',
    'eslint/no-this-before-super': 'error',
    'eslint/no-unassigned-vars': 'error',
    'eslint/no-unreachable': 'error',
    'eslint/no-unsafe-finally': 'error',
    'eslint/no-unsafe-negation': 'error',
    'eslint/no-unsafe-optional-chaining': 'error',
    'eslint/no-unused-expressions': 'error',
    'eslint/no-unused-labels': 'error',
    'eslint/no-unused-private-class-members': 'error',
    'eslint/no-unused-vars': [
      'error',
      { fix: { imports: 'safe-fix' }, ignoreRestSiblings: true },
    ],
    'eslint/no-useless-backreference': 'error',
    'eslint/no-useless-catch': 'error',
    'eslint/no-useless-escape': 'error',
    'eslint/no-useless-rename': 'error',
    'eslint/no-with': 'error',
    'eslint/require-yield': 'error',
    'eslint/use-isnan': 'error',
    'eslint/valid-typeof': 'error',

    // eslint – restriction
    'eslint/no-alert': 'error',
    'eslint/no-bitwise': 'error',
    'eslint/no-console': ['error', { allow: ['info', 'warn', 'error'] }],
    'eslint/no-empty': 'error',
    'eslint/no-empty-function': 'error',
    'eslint/no-eq-null': 'error',
    'eslint/no-implicit-globals': 'error',
    'eslint/no-param-reassign': 'error',
    'eslint/no-plusplus': 'error',
    'eslint/no-proto': 'error',
    'eslint/no-restricted-imports': [
      'error',
      { patterns: ['..', '../**/*', '@/*/*/*/**'] },
    ],
    'eslint/no-sequences': ['error', { allowInParentheses: false }],
    'eslint/no-use-before-define': [
      'error',
      { allowNamedExports: true, functions: false },
    ],
    'eslint/no-var': 'error',
    'eslint/no-void': ['error', { allowAsStatement: true }],
    'eslint/unicode-bom': 'error',

    // eslint – perf
    'eslint/no-useless-call': 'error',

    // eslint – suspicious
    'eslint/no-extend-native': 'error',
    'eslint/no-implied-eval': 'error',
    'eslint/no-new': 'error',
    'eslint/no-shadow': 'error',
    'eslint/no-underscore-dangle': 'error',
    'eslint/no-unexpected-multiline': 'error',
    'eslint/no-unmodified-loop-condition': 'error',
    'eslint/no-unneeded-ternary': 'error',
    'eslint/no-useless-concat': 'error',
    'eslint/preserve-caught-error': 'error',

    // eslint – pedantic
    'eslint/accessor-pairs': 'warn',
    'eslint/array-callback-return': ['warn', { allowImplicit: true }],
    'eslint/eqeqeq': ['warn', 'always', { null: 'ignore' }],
    'eslint/max-classes-per-file': 'warn',
    'eslint/max-depth': ['warn', { max: 3 }],
    'eslint/max-lines': [
      'warn',
      { max: 500, skipBlankLines: true, skipComments: true },
    ],
    'eslint/max-nested-callbacks': ['warn', { max: 3 }],
    'eslint/no-array-constructor': 'warn',
    'eslint/no-case-declarations': 'warn',
    'eslint/no-constructor-return': 'warn',
    'eslint/no-else-return': ['warn', { allowElseIf: false }],
    'eslint/no-fallthrough': 'warn',
    'eslint/no-inner-declarations': 'warn',
    'eslint/no-lonely-if': 'warn',
    'eslint/no-loop-func': 'warn',
    'eslint/no-negated-condition': 'warn',
    'eslint/no-new-wrappers': 'warn',
    'eslint/no-object-constructor': 'warn',
    'eslint/no-self-compare': 'warn',
    'eslint/no-useless-return': 'warn',
    'eslint/radix': 'warn',
    'eslint/symbol-description': 'warn',

    // eslint – style
    'eslint/curly': 'warn',
    'eslint/default-case-last': 'warn',
    'eslint/default-param-last': 'warn',
    'eslint/func-names': ['warn', 'always'],
    'eslint/func-style': ['warn', 'declaration'],
    'eslint/grouped-accessor-pairs': 'warn',
    'eslint/guard-for-in': 'warn',
    'eslint/id-length': ['error', { exceptions: ['a', 'b', 'i', 'j', '_'] }],
    'eslint/logical-assignment-operators': 'warn',
    'eslint/max-params': 'warn',
    'eslint/no-duplicate-imports': ['warn', { allowSeparateTypeImports: true }],
    'eslint/no-extra-label': 'warn',
    'eslint/no-implicit-coercion': 'warn',
    'eslint/no-label-var': 'warn',
    'eslint/no-lone-blocks': 'warn',
    'eslint/no-multi-assign': 'warn',
    'eslint/no-multi-str': 'warn',
    'eslint/no-new-func': 'warn',
    'eslint/no-return-assign': 'warn',
    'eslint/no-script-url': 'warn',
    'eslint/no-template-curly-in-string': 'warn',
    'eslint/no-useless-computed-key': 'warn',
    'eslint/object-shorthand': 'warn',
    'eslint/operator-assignment': 'warn',
    'eslint/prefer-arrow-callback': ['warn', { allowNamedFunctions: true }],
    'eslint/prefer-const': 'warn',
    'eslint/prefer-destructuring': 'warn',
    'eslint/prefer-exponentiation-operator': 'warn',
    'eslint/prefer-named-capture-group': 'warn',
    'eslint/prefer-numeric-literals': 'warn',
    'eslint/prefer-object-has-own': 'warn',
    'eslint/prefer-object-spread': 'warn',
    'eslint/prefer-promise-reject-errors': 'warn',
    'eslint/prefer-regex-literals': 'warn',
    'eslint/prefer-rest-params': 'warn',
    'eslint/prefer-spread': 'warn',
    'eslint/prefer-template': 'warn',
    'eslint/yoda': 'warn',

    // eslint – nursery
    'eslint/no-unreachable-loop': 'warn',
    'eslint/no-useless-assignment': 'warn',

    // typescript – correctness
    'typescript/await-thenable': 'error',
    'typescript/no-array-delete': 'error',
    'typescript/no-base-to-string': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    'typescript/no-meaningless-void-operator': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-misused-spread': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-redundant-type-constituents': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-parameter-property-assignment': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-unary-minus': 'error',
    'typescript/no-useless-default-assignment': 'error',
    'typescript/no-useless-empty-export': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/require-array-sort-compare': 'error',
    'typescript/restrict-template-expressions': [
      'error',
      {
        allowAny: false,
        allowArray: false,
        allowBoolean: false,
        allowNever: false,
        allowNullish: false,
        allowNumber: true,
        allowRegExp: false,
      },
    ],
    'typescript/triple-slash-reference': 'error',
    'typescript/unbound-method': 'error',

    // typescript – restriction
    'typescript/explicit-member-accessibility': [
      'error',
      { accessibility: 'no-public' },
    ],
    'typescript/no-dynamic-delete': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-invalid-void-type': [
      'error',
      { allowInGenericTypeArguments: true },
    ],
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-var-requires': 'error',
    'typescript/non-nullable-type-assertion-style': 'error',
    'typescript/prefer-literal-enum-member': [
      'error',
      { allowBitwiseExpressions: true },
    ],
    'typescript/use-unknown-in-catch-callback-variable': 'error',

    // typescript – suspicious
    'typescript/no-extraneous-class': 'error',
    'typescript/no-unnecessary-boolean-literal-compare': 'error',
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unnecessary-type-arguments': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unnecessary-type-conversion': 'error',
    'typescript/no-unnecessary-type-parameters': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-type-assertion': 'error',

    // typescript – pedantic
    'typescript/ban-ts-comment': 'warn',
    'typescript/no-confusing-void-expression': [
      'warn',
      { ignoreArrowShorthand: true, ignoreVoidReturningFunctions: true },
    ],
    'typescript/no-deprecated': 'warn',
    'typescript/no-misused-promises': ['warn', { checksVoidReturn: false }],
    'typescript/no-mixed-enums': 'warn',
    'typescript/no-unsafe-argument': 'warn',
    'typescript/no-unsafe-assignment': 'warn',
    'typescript/no-unsafe-call': 'warn',
    'typescript/no-unsafe-function-type': 'warn',
    'typescript/no-unsafe-member-access': 'warn',
    'typescript/no-unsafe-return': 'warn',
    'typescript/only-throw-error': 'warn',
    'typescript/prefer-enum-initializers': 'warn',
    'typescript/prefer-includes': 'warn',
    'typescript/prefer-nullish-coalescing': [
      'warn',
      {
        ignorePrimitives: {
          boolean: true,
          string: true,
        },
      },
    ],
    'typescript/prefer-promise-reject-errors': 'warn',
    'typescript/require-await': 'warn',
    'typescript/restrict-plus-operands': 'warn',
    'typescript/return-await': ['warn', 'error-handling-correctness-only'],
    'typescript/switch-exhaustiveness-check': 'warn',

    // typescript – style
    'typescript/adjacent-overload-signatures': 'warn',
    'typescript/array-type': 'warn',
    'typescript/class-literal-property-style': 'warn',
    'typescript/consistent-type-assertions': 'warn',
    'typescript/consistent-type-exports': 'warn',
    'typescript/consistent-type-imports': 'warn',
    'typescript/dot-notation': 'warn',
    'typescript/method-signature-style': 'warn',
    'typescript/no-empty-interface': 'warn',
    'typescript/no-inferrable-types': 'warn',
    'typescript/no-unnecessary-qualifier': 'warn',
    'typescript/parameter-properties': 'warn',
    'typescript/prefer-find': 'warn',
    'typescript/prefer-for-of': 'warn',
    'typescript/prefer-readonly': 'warn',
    'typescript/prefer-reduce-type-parameter': 'warn',
    'typescript/prefer-regexp-exec': 'warn',
    'typescript/prefer-return-this-type': 'warn',
    'typescript/prefer-string-starts-ends-with': 'warn',
    'typescript/unified-signatures': 'warn',

    // typescript – nursery
    'typescript/no-unnecessary-condition': 'warn',
    'typescript/prefer-optional-chain': 'warn',

    // unicorn – correctness
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/no-empty-file': 'error',
    'unicorn/no-invalid-fetch-options': 'error',
    'unicorn/no-invalid-remove-event-listener': 'error',
    'unicorn/no-new-array': 'error',
    'unicorn/no-single-promise-in-promise-methods': 'error',
    'unicorn/no-thenable': 'error',
    'unicorn/no-unnecessary-await': 'error',
    'unicorn/no-useless-fallback-in-spread': 'error',
    'unicorn/no-useless-length-check': 'error',
    'unicorn/no-useless-spread': 'error',
    'unicorn/prefer-set-size': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',

    // unicorn – restriction
    'unicorn/no-abusive-eslint-disable': 'error',
    'unicorn/no-array-for-each': 'error',
    'unicorn/no-array-reduce': 'error',
    'unicorn/no-document-cookie': 'error',
    'unicorn/no-length-as-slice-end': 'error',
    'unicorn/no-magic-array-flat-depth': 'error',
    'unicorn/no-process-exit': 'error',
    'unicorn/no-useless-error-capture-stack-trace': 'error',
    'unicorn/prefer-modern-math-apis': 'error',
    'unicorn/prefer-module': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-number-properties': 'error',

    // unicorn – perf
    'unicorn/prefer-array-find': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-set-has': 'error',

    // unicorn – suspicious
    'unicorn/consistent-function-scoping': 'error',
    'unicorn/no-accessor-recursion': 'error',
    'unicorn/no-array-fill-with-reference-type': 'error',
    'unicorn/no-array-reverse': 'error',
    'unicorn/no-array-sort': ['error', { allowAfterSpread: true }],
    'unicorn/no-confusing-array-with': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/prefer-add-event-listener': 'error',
    'unicorn/require-module-specifiers': 'error',

    // unicorn – pedantic
    'unicorn/consistent-empty-array-spread': 'warn',
    'unicorn/escape-case': 'warn',
    'unicorn/explicit-length-check': 'warn',
    'unicorn/new-for-builtins': 'warn',
    'unicorn/no-array-callback-reference': 'warn',
    'unicorn/no-hex-escape': 'warn',
    'unicorn/no-immediate-mutation': 'warn',
    'unicorn/no-instanceof-array': 'warn',
    'unicorn/no-lonely-if': 'warn',
    'unicorn/no-negation-in-equality-check': 'warn',
    'unicorn/no-new-buffer': 'warn',
    'unicorn/no-object-as-default-parameter': 'warn',
    'unicorn/no-static-only-class': 'warn',
    'unicorn/no-this-assignment': 'warn',
    'unicorn/no-typeof-undefined': 'warn',
    'unicorn/no-unnecessary-array-flat-depth': 'warn',
    'unicorn/no-unnecessary-array-splice-count': 'warn',
    'unicorn/no-unnecessary-slice-end': 'warn',
    'unicorn/no-unreadable-iife': 'warn',
    'unicorn/no-useless-promise-resolve-reject': 'warn',
    'unicorn/no-useless-switch-case': 'warn',
    'unicorn/no-useless-undefined': ['warn', { checkArguments: false }],
    'unicorn/prefer-array-flat': 'warn',
    'unicorn/prefer-array-some': 'warn',
    'unicorn/prefer-at': 'warn',
    'unicorn/prefer-blob-reading-methods': 'warn',
    'unicorn/prefer-code-point': 'warn',
    'unicorn/prefer-date-now': 'warn',
    'unicorn/prefer-dom-node-append': 'warn',
    'unicorn/prefer-dom-node-dataset': 'warn',
    'unicorn/prefer-dom-node-remove': 'warn',
    'unicorn/prefer-event-target': 'warn',
    'unicorn/prefer-import-meta-properties': 'warn',
    'unicorn/prefer-math-min-max': 'warn',
    'unicorn/prefer-math-trunc': 'warn',
    'unicorn/prefer-native-coercion-functions': 'warn',
    'unicorn/prefer-prototype-methods': 'warn',
    'unicorn/prefer-query-selector': 'warn',
    'unicorn/prefer-regexp-test': 'warn',
    'unicorn/prefer-single-call': 'warn',
    'unicorn/prefer-string-replace-all': 'warn',
    'unicorn/prefer-string-slice': 'warn',
    'unicorn/prefer-top-level-await': 'warn',
    'unicorn/prefer-type-error': 'warn',
    'unicorn/require-number-to-fixed-digits-argument': 'warn',

    // unicorn – style
    'unicorn/catch-error-name': 'warn',
    'unicorn/consistent-date-clone': 'warn',
    'unicorn/consistent-existence-index-check': 'warn',
    'unicorn/consistent-template-literal-escape': 'warn',
    'unicorn/custom-error-definition': 'warn',
    'unicorn/error-message': 'warn',
    'unicorn/explicit-timer-delay': 'warn',
    'unicorn/filename-case': 'warn',
    'unicorn/max-nested-calls': 'warn',
    'unicorn/no-array-method-this-argument': 'warn',
    'unicorn/no-await-expression-member': 'warn',
    'unicorn/no-console-spaces': 'warn',
    'unicorn/no-unreadable-array-destructuring': 'warn',
    'unicorn/no-useless-collection-argument': 'warn',
    'unicorn/no-zero-fractions': 'warn',
    'unicorn/number-literal-case': 'warn',
    'unicorn/numeric-separators-style': 'warn',
    'unicorn/prefer-array-index-of': 'warn',
    'unicorn/prefer-bigint-literals': 'warn',
    'unicorn/prefer-class-fields': 'warn',
    'unicorn/prefer-classlist-toggle': 'warn',
    'unicorn/prefer-default-parameters': 'warn',
    'unicorn/prefer-dom-node-text-content': 'warn',
    'unicorn/prefer-export-from': 'warn',
    'unicorn/prefer-global-this': 'warn',
    'unicorn/prefer-includes': 'warn',
    'unicorn/prefer-keyboard-event-key': 'warn',
    'unicorn/prefer-logical-operator-over-ternary': 'warn',
    'unicorn/prefer-modern-dom-apis': 'warn',
    'unicorn/prefer-negative-index': 'warn',
    'unicorn/prefer-object-from-entries': 'warn',
    'unicorn/prefer-optional-catch-binding': 'warn',
    'unicorn/prefer-reflect-apply': 'warn',
    'unicorn/prefer-response-static-json': 'warn',
    'unicorn/prefer-spread': 'warn',
    'unicorn/prefer-string-raw': 'warn',
    'unicorn/prefer-string-trim-start-end': 'warn',
    'unicorn/prefer-structured-clone': 'warn',
    'unicorn/prefer-ternary': 'warn',
    'unicorn/relative-url-style': 'warn',
    'unicorn/require-array-join-separator': 'warn',
    'unicorn/require-module-attributes': 'warn',
    'unicorn/switch-case-braces': 'warn',
    'unicorn/switch-case-break-position': 'warn',
    'unicorn/text-encoding-identifier-case': 'warn',
    'unicorn/throw-new-error': 'warn',

    // unicorn – nursery
    'unicorn/no-useless-iterator-to-array': 'warn',

    // oxc – correctness
    'oxc/bad-array-method-on-arguments': 'error',
    'oxc/bad-char-at-comparison': 'error',
    'oxc/bad-comparison-sequence': 'error',
    'oxc/bad-min-max-func': 'error',
    'oxc/bad-object-literal-comparison': 'error',
    'oxc/bad-replace-all-arg': 'error',
    'oxc/const-comparisons': 'error',
    'oxc/double-comparisons': 'error',
    'oxc/erasing-op': 'error',
    'oxc/missing-throw': 'error',
    'oxc/number-arg-out-of-range': 'error',
    'oxc/only-used-in-recursion': 'error',
    'oxc/uninvoked-array-callback': 'error',

    // oxc – restriction
    'oxc/bad-bitwise-operator': 'error',

    // oxc – perf
    'oxc/no-accumulating-spread': 'error',
    'oxc/no-map-spread': 'error',

    // oxc – suspicious
    'oxc/approx-constant': 'error',
    'oxc/misrefactored-assign-op': 'error',
    'oxc/no-this-in-exported-function': 'error',

    // oxc – pedantic
    'oxc/branches-sharing-code': 'warn',

    // import – correctness
    'import/default': 'error',
    'import/namespace': 'error',

    // import – restriction
    'import/extensions': [
      'error',
      'always',
      { checkTypeImports: true, ignorePackages: true },
    ],
    'import/no-amd': 'error',
    'import/no-commonjs': 'error',
    'import/no-default-export': 'error',
    'import/no-dynamic-require': 'error',
    'import/no-relative-parent-imports': 'error',
    'import/no-webpack-loader-syntax': 'error',
    'import/unambiguous': 'error',

    // import – suspicious
    'import/no-absolute-path': 'error',
    'import/no-empty-named-blocks': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-self-import': 'error',

    // import – style
    'import/consistent-type-specifier-style': 'warn',
    'import/first': 'warn',
    'import/newline-after-import': ['warn', { considerComments: true }],
    'import/no-anonymous-default-export': 'warn',
    'import/no-duplicates': 'warn',
    'import/no-mutable-exports': 'warn',
    'import/no-named-default': 'warn',

    // import – nursery
    'import/export': 'warn',
    'import/named': 'warn',

    // jsdoc – correctness
    'jsdoc/check-property-names': 'error',
    'jsdoc/check-tag-names': 'error',
    'jsdoc/implements-on-classes': 'error',
    'jsdoc/no-defaults': 'error',
    'jsdoc/require-property': 'error',
    'jsdoc/require-property-description': 'error',
    'jsdoc/require-property-name': 'error',
    'jsdoc/require-property-type': 'error',
    'jsdoc/require-yields': 'error',

    // jsdoc – restriction
    'jsdoc/check-access': 'error',
    'jsdoc/empty-tags': 'error',

    // jsdoc – pedantic
    'jsdoc/require-param': 'warn',
    'jsdoc/require-param-description': 'warn',
    'jsdoc/require-param-name': 'warn',
    'jsdoc/require-param-type': 'warn',
    'jsdoc/require-returns': 'warn',
    'jsdoc/require-returns-description': 'warn',
    'jsdoc/require-returns-type': 'warn',
    'jsdoc/require-throws-type': 'warn',
    'jsdoc/require-yields-type': 'warn',

    // jsdoc – style
    'jsdoc/require-throws-description': 'warn',
    'jsdoc/require-yields-description': 'warn',

    // jsx-a11y – correctness
    'jsx-a11y/alt-text': 'error',
    'jsx-a11y/anchor-has-content': 'error',
    'jsx-a11y/anchor-is-valid': 'error',
    'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-proptypes': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/aria-unsupported-elements': 'error',
    'jsx-a11y/autocomplete-valid': 'error',
    'jsx-a11y/click-events-have-key-events': 'error',
    'jsx-a11y/control-has-associated-label': 'error',
    'jsx-a11y/heading-has-content': 'error',
    'jsx-a11y/html-has-lang': 'error',
    'jsx-a11y/iframe-has-title': 'error',
    'jsx-a11y/img-redundant-alt': [
      'error',
      { words: ['фото', 'фотография', 'изображение', 'картинка'] },
    ],
    'jsx-a11y/interactive-supports-focus': 'error',
    'jsx-a11y/label-has-associated-control': 'error',
    'jsx-a11y/lang': 'error',
    'jsx-a11y/media-has-caption': 'error',
    'jsx-a11y/mouse-events-have-key-events': 'error',
    'jsx-a11y/no-access-key': 'error',
    'jsx-a11y/no-aria-hidden-on-focusable': 'error',
    'jsx-a11y/no-autofocus': 'error',
    'jsx-a11y/no-distracting-elements': 'error',
    'jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
    'jsx-a11y/no-noninteractive-element-interactions': 'error',
    'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
    'jsx-a11y/no-noninteractive-tabindex': 'error',
    'jsx-a11y/no-redundant-roles': 'error',
    'jsx-a11y/no-static-element-interactions': 'error',
    'jsx-a11y/prefer-tag-over-role': 'error',
    'jsx-a11y/role-has-required-aria-props': 'error',
    'jsx-a11y/role-supports-aria-props': 'error',
    'jsx-a11y/scope': 'error',
    'jsx-a11y/tabindex-no-positive': 'error',

    // promise – correctness
    'promise/no-callback-in-promise': 'error',
    'promise/no-new-statics': 'error',
    'promise/valid-params': 'error',

    // promise – restriction
    'promise/catch-or-return': ['error', { allowFinally: true }],
    'promise/spec-only': 'error',

    // promise – suspicious
    'promise/always-return': ['error', { ignoreLastCallback: true }],
    'promise/no-multiple-resolved': 'error',
    'promise/no-promise-in-callback': 'error',

    // promise – style
    // "promise/avoid-new": "error", // arguable
    'promise/no-nesting': 'warn',
    'promise/no-return-wrap': 'warn',
    'promise/param-names': 'warn',
    'promise/prefer-await-to-callbacks': 'warn',
    // "promise/prefer-await-to-then": "error", // arguable
    'promise/prefer-catch': 'warn',

    // promise – nursery
    'promise/no-return-in-finally': 'warn',

    // sonarjs-js
    'sonarjs-js/anchor-precedence': 'error',
    'sonarjs-js/class-name': 'error',
    'sonarjs-js/cognitive-complexity': 'error',
    'sonarjs-js/concise-regex': 'error',
    'sonarjs-js/cookie-no-httponly': 'error',
    'sonarjs-js/disabled-resource-integrity': 'error',
    'sonarjs-js/duplicates-in-character-class': 'error',
    'sonarjs-js/dynamically-constructed-templates': 'error',
    'sonarjs-js/empty-string-repetition': 'error',
    'sonarjs-js/encryption-secure-mode': 'error',
    'sonarjs-js/existing-groups': 'error',
    'sonarjs-js/fixme-tag': 'error',
    'sonarjs-js/hashing': 'error',
    'sonarjs-js/hidden-files': 'error',
    'sonarjs-js/insecure-cookie': 'error',
    'sonarjs-js/insecure-jwt-token': 'error',
    'sonarjs-js/inverted-assertion-arguments': 'error',
    'sonarjs-js/jsx-no-leaked-render': 'error',
    'sonarjs-js/max-switch-cases': 'error',
    'sonarjs-js/misplaced-loop-counter': 'error',
    'sonarjs-js/no-all-duplicated-branches': 'error',
    'sonarjs-js/no-duplicated-branches': 'error',
    'sonarjs-js/no-element-overwrite': 'error',
    'sonarjs-js/no-empty-after-reluctant': 'error',
    'sonarjs-js/no-empty-group': 'error',
    'sonarjs-js/no-empty-test-file': 'error',
    'sonarjs-js/no-identical-expressions': 'error',
    'sonarjs-js/no-implicit-global': 'error',
    'sonarjs-js/no-invariant-returns': 'error',
    'sonarjs-js/no-nested-template-literals': 'error',
    'sonarjs-js/no-regex-spaces': 'error',
    'sonarjs-js/no-small-switch': 'error',
    'sonarjs-js/no-try-promise': 'error',
    'sonarjs-js/no-uniq-key': 'error',
    'sonarjs-js/no-use-of-empty-return-value': 'error',
    'sonarjs-js/non-existent-operator': 'error',
    'sonarjs-js/prefer-default-last': 'error',
    'sonarjs-js/prefer-promise-shorthand': 'error',
    'sonarjs-js/prefer-single-boolean-return': 'error',
    'sonarjs-js/prefer-type-guard': 'error',
    'sonarjs-js/prefer-while': 'error',
    'sonarjs-js/public-static-readonly': 'error',
    'sonarjs-js/reduce-initial-value': 'error',
    'sonarjs-js/single-char-in-character-classes': 'error',
    'sonarjs-js/single-character-alternation': 'error',
    'sonarjs-js/slow-regex': 'error',
    'sonarjs-js/table-header': 'error',
    'sonarjs-js/table-header-reference': 'error',
    'sonarjs-js/todo-tag': 'warn',
    'sonarjs-js/unused-named-groups': 'error',
  },
  overrides: [
    {
      files: ['**/*.config.*'],
      rules: {
        'eslint/max-lines': 'off',
        'import/no-default-export': 'off',
      },
    },
    {
      files: ['**/*.mocks.*', '**/*.fixtures.*'],
      rules: {
        'eslint/id-length': 'off',
        'eslint/max-lines': 'off',
      },
    },
  ],
})
